replicaCount: 1
env: development

image:
  repository: registry-intl.ap-southeast-1.aliyuncs.com/dimzrio/numbersapi:frontend
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: numbersapi.example.com
      paths: 
        - /*

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

backendURL: backend.development.svc.cluster.local:8080/info